### ISSUE TITLE
IPA Error 3003: ZeroArgumentError

### ISSUE THREAD

**Issue by stopkadr** [Carbenium/freeipa-mailserver#3]
**Bug Report**

What happened:
Hi,
Got IPA Error 3003: ZeroArgumentError (command 'dovecotconfig_mod' takes no arguments) when tried update mailbox quota value 
and   
Got IPA Error 3003: ZeroArgumentError (command 'postfixconfig_mod' takes no arguments) when tried add virtual domain

FreeIPA: version: 4.8.4
OS: CentOS Linux release 8.2.2004 (Core) / Red Hat Enterprise Linux release 8.2 (Ootpa)

Could you help resolve this issue?
Thanks

![Selection_185](https://user-images.githubusercontent.com/1748940/92900511-6d6dc100-f428-11ea-82ad-55963dcfa740.png)
![Selection_186](https://user-images.githubusercontent.com/1748940/92900531-71014800-f428-11ea-82a3-50c511e7eaa7.png)

**Comment by Carbenium** [comment]
Thanks for the report! Version [0.2.3](https://github.com/SOSETH/freeipa-mailserver/releases/tag/freeipa-mailserver-0.2.3-1) should fix the issue.
