### ISSUE TITLE
Is this project still up-to-date?

### ISSUE THREAD

**Issue by epigraphe** [Carbenium/freeipa-mailserver#4]
Good day.
Is this project still up-to-date? I was able to install it, but in the settings I can only create domains and default transport. The mail section in the user profile is not active.

**Comment by epigraphe** [comment]
I'm sorry, I figured out how everything works. I believe the plugin is up to date. thank

**Comment by epigraphe** [comment]
Although the question remained.
How to set up a domain alias? I added it in the FREEIPA admin area, but now I can't figure out how to make the postfix handle it.
What needs to be done next, tell me, please

**Comment by Carbenium** [comment]
Yes, this module is still maintained! I use it actively.

Hints for how to configure postfix and dovecot can be found in [this Ansible role](https://github.com/SOSETH/mailserver/tree/ldap). Since postfix/dovecot configurations can be quite custom, there is not really a step-by-step guide.
