### ISSUE TITLE
Lower required Python version / Provide builds for Rocky&Alma

### ISSUE THREAD

**Issue by flortsch** [Carbenium/freeipa-mailserver#5]
Hello,

first of all, thanks for this extensions that allows defining more advances mail settings in FreeIPA :)
I am evaluating this extension for my FreeIPA installation that runs on a Rocky Linux 9 server.
This version of Rocky only provides Python 3.9 out of the box - older verions like Rocky 8 only provide Python 3.6.

Would it be possible to lower the required Python version (last release based on F35 needs Python 3.10) or provide different builds, so users of distros like Rocky&Alma could also make use of this FreeIPA extension without installing additional Python versions?

Cheers,
Florian

**Comment by Carbenium** [comment]
Hi Florian!

I'm very sorry about the delayed answer...

I set up a copr repository over at https://copr.fedorainfracloud.org/coprs/carbenium/freeipa-mailserver/
There you'll packages built against RHEL 8 and 9 in addition to Fedora builds.

Let me know if that works for you. I didn't test those packages yet, so let me know if something needs to be adjusted.

**Comment by flortsch** [comment]
No worries! Thx for your reply and your effort, will check this out and report back :)
